export const actionTypes ={
  SET_PRODUCTS :"SET_PRODUCTS",
  SELECTED_PRODUCTS : "SELECTED_PRODUCTS",
  REMOVE_SELECTED :"REMOVE_SELECTED",
  ADD_TO_CART : "ADD_TO_CART",
  REMOVE_FROM_CART:"REMOVE_FROM_CART",
  UPDATE_CART_QUANTITY:"UPDATE_CART_QUANTITY",
  CURRENT_ITEM:"CURRENT_ITEM"
}